### ISSUE TITLE
Failed to download old elpa packages

### ISSUE THREAD

**Issue by Vonfry** [nix-community/emacs-overlay#100]
The problem is mainly for those who use emacs with stable nixpkgs branch.

The old packages on elpa is packed by `tlz` named `<pkg>.tar.lz`, and the current one is named `<pkg>.tar`, such as [auctex](http://elpa.gnu.org/packages/auctex.html). Could it be reproducable for the stable one when downloading from elpa?

**Comment by talyz** [comment]
This sounds more like a question for the [`emacs2nix`](https://github.com/ttuegel/emacs2nix) project and `nixpkgs`. I don't think there are any good ways to get rid of breakage, other than using alternative mirrors, since the old versions are provided as new files. The latest package isn't available as a `tar.lz` - if it had been, switching to it would have solved the issue.

**Comment by Vonfry** [comment]
Ref: ttuegel/emacs2nix#55 & NixOS/nixpkgs/issues#110796
