### ISSUE TITLE
*Gcc packages does print errors for packages during build

### ISSUE THREAD

**Issue by NobbZ** [nix-community/emacs-overlay#120]
When using `emacsGgg` or `emacsPgtkGcc` in my config, I get errors like the following during compilition of most, if not all, packages:

```plain
emacs-magit> Debugger entered--Lisp error: (native-compiler-error-empty-byte "/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-..." "/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-...")
emacs-magit>   signal(native-compiler-error-empty-byte ("/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-..." "/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-..."))
emacs-magit>   comp--native-compile("/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-...")
emacs-magit>   batch-native-compile()
emacs-magit>   command-line-1(("-f" "batch-native-compile" "/nix/store/f54kjchgzmf7dz6yikph9c0f65yagks6-emacs-..."))
emacs-magit>   command-line()
emacs-magit>   normal-top-level()
```

It seems as if the pathes are indeed different for each package.

Is there a way to make the packages compile correctly?

I'm observing this behaviour for a while now (approx half a year), though now I found the time to actually create an issue about it.

At least on a first glance, there are no additional runtime issues. (I was able to open some random files in emacs without having any errors or warning in the message buffer that haven't been there before)

**Comment by collares** [comment]
This is arguably not an error, even if it says "error" on the message. The Nix native compilation step asks emacs to native-compile every .el file, and all this message is saying is that an .el file didn't have anything interesting to compile (in technical terms, it didn't contain any top-level forms).  If you byte-compile such a file you'll also get no .elc file because there's nothing to byte-compile; the native-compiler is just emitting an overzealous warning. This does not stop compilation, and everything that can be compiled is being compiled if you don't see any other types of errors.

Probably we should ask upstream to turn this error into a warning, but I already bother the gccemacs maintainer enough :)

**Comment by NobbZ** [comment]
Thanks for the explanation!

Yes, this should indeed be fixed upstream then. Though I am not used to the emacs processes to report a bug/issue with GccEmacs or Emacs at all…

**Comment by collares** [comment]
Reported this upstream at http://debbugs.gnu.org/cgi/bugreport.cgi?bug=47169

**Comment by collares** [comment]
@NobbZ Thanks for the bug report! The gccemacs maintainer fixed this upstream, so `emacsGcc` should not emit as many `native-compiler-error-empty-byte` errors, if any. Eventually this will get merged to `emacsPgtkGcc`.
