### ISSUE TITLE
No updates in 5 days

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#126]
It's been several days since any of the attempted auto-updates to the overlay built successfully.

**Comment by Mic92** [comment]
I think this fall into the time window when we upgraded hydra. We also had a downtime the last two days
due to https://github.com/NixOS/nixpkgs/pull/117618#issue-601059733

@grahamc do you know what I should look at to see why hydra is no longer processing builds? https://hydra.nix-community.org/queue-summary

**Comment by spacekitteh** [comment]
Any movement on this?

**Comment by Mic92** [comment]
After restarting queued-build-hook I see some builds getting processed again: https://github.com/nix-community/infra/commit/b0a9ac3a524353a876966c0459091efefbbe8e1cg 

Let's see how it goes.

**Comment by Mic92** [comment]
The queue is empty!

**Comment by spacekitteh** [comment]
But it's still no update in 11 days now?

**Comment by spacekitteh** [comment]
@adisbladis @Mic92 ?

**Comment by Mic92** [comment]
As far as I understand a gitlab ci runner is handling the repository updates: https://github.com/nix-community/emacs-overlay/blob/d9530a7048f4b1c0f65825202a0ce1d111a1d39a/.gitlab-ci.yml#L3
However I don't know where this is triggered from. @adisbladis or @talyz might know? It could be also ported to github actions these days...

**Comment by spacekitteh** [comment]
Could this be re-opened until it's actually fixed?

**Comment by nuance** [comment]
Note that this is fixed in my repo (I'm using it via a flake `github:nuance/emacs-overlay-test-action`) and the daily action from the PR is running there. I plan on deleting that repo whenever this is back to updating and don't plan on supporting it, but feel free to use that if you need updates before this gets fixed.

I'm not sure what else happens in the gitlab builder right now that isn't replicated in my PR / GitHub Actions.

**Comment by talyz** [comment]
@Mic92 It's triggered on a schedule, every four hours. Looking at the jobs, it looks like network / resolver configuration issues: https://gitlab.com/nix-community/emacs-overlay/-/jobs

**Comment by Mic92** [comment]
Opened an issue here: https://github.com/nix-community/infra/issues/80

**Comment by Mic92** [comment]
Seems to work now.
