### ISSUE TITLE
Ignore use-package declarations with :disabled t

### ISSUE THREAD

**Issue by benley** [nix-community/emacs-overlay#15]
Somewhat related to #6.

In my config are several use-package invocations with `:disabled t`, so use-package ignores them.  Commenting them out would have nearly the same effect, so that can be my workaround, but it would be handy (and probably not _that_ hard to implement for most cases?) if `emacsWithPackagesFromUsePackage` could just ignore them on its own.

**Comment by adisbladis** [comment]
I know that @talyz was working on a proper emacs lisp parser in Nix. Once we have that we can start supporting all sorts of interesting use-package features.

**Comment by akirak** [comment]
> I know that @talyz was working on a proper emacs lisp parser in Nix. Once we have that we can start supporting all sorts of interesting use-package features.

How is this going on? I'm now trying out `emacsWithPackagesFromUsePackage` and quite interested in it.

**Comment by purcell** [comment]
> I know that @talyz was working on a proper emacs lisp parser in Nix. Once we have that we can start supporting all sorts of interesting use-package features.

I'd be keen to get my hands on such a parser for purposes like #38, but I'd be wary of expecting that it would allow robust support of various `use-package` features, since values passed to `:disabled`, :if` etc. can be expressions that would need to be evaluated to know their values. A simple example would be `:if (eq system-type 'darwin)`. Without evaluation, users will always need to craft their Emacs init files a certain way to avoid such issues when inspected by `emacs-overlay` functions.

**Comment by talyz** [comment]
The Elisp parser is now finished and available [here](https://github.com/talyz/fromElisp). I've also opened a PR, #43, which uses it to parse `use-package` declarations and respects `:disabled` as best it can - as @purcell says, it doesn't evaluate the code and can therefore not respect anything more advanced than simple boolean literals.
