### ISSUE TITLE
No successful updates to Emacs master since May 10

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#150]
The last successful update of Emacs master to the overlay occurred several days ago. Since then, Melpa and Elpa updates have proceeded normally, but Emacs updates have not been reflected in the overlay.

**Comment by jboyens** [comment]
If you're using one of the emacsGcc or emacsPgtkGcc packages it's probably due to #147 or #148.

I ended up switching to emacsPgtk to get my system building again.

**Comment by talyz** [comment]
This is due to the `emacsPgtkGcc` package failing to build, due to the inverse problem of #147 - the changes required for the fix submitted in https://github.com/NixOS/nixpkgs/pull/121954 are not yet merged into the `feature/pgtk` branch upstream. If one emacs package fails to build, they all do. This will resolve itself when the `feature/pgtk` branch is brought up-to-date with `master`.

**Comment by talyz** [comment]
Let's keep this open until the branches are merged.
