### ISSUE TITLE
packages.system.emacsUnstable isn't very bleeding edge 

### ISSUE THREAD

**Issue by jasonjckn** [nix-community/emacs-overlay#271]
```
 nix shell --no-write-lock-file github:nix-community/emacs-overlay\#emacsUnstable -c emacs --version

```

tries to install emacs v28.2, for a "bleeding edge" repo, with "unstable", doesn't seem appropriate 

if you think this is a valid issue, I can send a PR

**Comment by jasonjckn** [comment]
looking at the source code more, i guess this is intentional, 'stable' would be a better word then.

**Comment by leungbk** [comment]
> looking at the source code more, i guess this is intentional, 'stable' would be a better word then.

It isn't always going to be stable since a "tag" as defined by https://github.com/nix-community/emacs-overlay/blob/0743ae0eb85b4e1087fc20fd0c9bcf8efb1fdc4f/repos/emacs/update#L45

may end up corresponding to a pre-release candidate like 28.0.91.

One thing we could try is to do something like `git branch --remotes --list 'origin/emacs-*'`, resulting in 

```
  origin/emacs-23
  origin/emacs-24
  origin/emacs-25
  origin/emacs-26
  origin/emacs-27
  origin/emacs-28
  origin/emacs-29
```

and then sort + etc. That way we still get bug-fix commits and the like on our "unstable" branch. Maybe @adisbladis has some thoughts on this.

**Comment by andersk** [comment]
`emacsUnstable` is now 29.0.90, released this Monday.
