### ISSUE TITLE
Cannot install emacs using this overlay

### ISSUE THREAD

**Issue by morphykuffour** [nix-community/emacs-overlay#291]
I am currently on NixOS  version 23.05.20230104.9813adc (Stoat) and I am trying to use this overlay in order to install emacs and get access to `emacsWithPackagesFromUsePackage` functionality in order to install packages using nix declaratively. I am running into the following errors and any help would be greatly appreciated. I have looked through some of the issues I think it pertains to the version of nixos I am currently running.

This is a link to my config for this emacs overlay: https://github.com/morphykuffour/nix/blob/main/hosts/win-wsl/configuration.nix#L114

![image](https://user-images.githubusercontent.com/23323356/211091333-389466f5-72ca-43bc-8cca-82036efba232.png)

**Comment by dschrempf** [comment]
Hi! The actual build error is not visible in your log. The build error could occur because you are using WSL, it could also be that the revision on the Emacs master branch had a build error.

For a first step, I would try using `emacsUnstable` (or even better a stable version) instead of `emacsGit`. If this also fails, you may want to report the complete debug log showing the error.

**Comment by adisbladis** [comment]
Closing as this doesn't seem actionable on our end.
