### ISSUE TITLE
epkg requires sqlite

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/emacs-overlay#296]
`epkgs.melpaPackages.epkg` [requires the `sqlite3` binary](https://github.com/emacscollective/epkg/blob/361c2545443e9b8e89090b2d3ad8558d41f3ed70/lisp/epkg.el#L154) in `PATH`. This binary comes with the `sqlite` nixpkgs package.

Is it possible to add a non-Emacs package as a dependency to `epkg`?

**Comment by talyz** [comment]
The easiest solution would probably be to patch the file with `substituteInPlace`. However, this should be fixed in nixpkgs, in the [melpa-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/melpa-packages.nix) file. In that file, there are a few similar fixes already, such as [this one for racer](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/melpa-packages.nix#L527-L532).

**Comment by DamienCassou** [comment]
@talyz thank you very much for your answer. I have prepared a patch for nixpkgs but it doesn't seem to affect the epkg package I get from emacs-overlay. What is the relationship between both?

My patch:

```nix
{
    epkg = super.epkg.overrideAttrs (old: {
      postPatch = ''
        substituteXXInPlace epkg.el '"sqlite3"' '"${pkgs.sqlite}/bin/sqlite3"'
      '';
    });
}
```

As you can see with `substituteXXInPlace`, I would expect installation of `epkg` to crash but it works fine.

Here is my home-manager config:

```nix
{ pkgs, ... }:

let
  emacsCore = pkgs.emacsUnstable.overrideAttrs (old: {
    patches = [];
  });
  melpaPackages = allMelpaPackages:
    with allMelpaPackages; [
      epkg
    ];
  emacsWithPackages = (pkgs.emacsPackagesFor emacsCore).emacsWithPackages
    (epkgs: (melpaPackages epkgs.melpaPackages));

in {
  programs.emacs = {
    enable = true;
    package = emacsWithPackages;
  };
}
```

Is there something I'm doing wrong?

**Comment by DamienCassou** [comment]
Please forget it: I just applied my changes to the wrong repository :-).

**Comment by DamienCassou** [comment]
@talyz PR opened: https://github.com/NixOS/nixpkgs/pull/215647
