### ISSUE TITLE
Why is emacsWithPackagesFromUsePackage part of the "emacs" overlay?

### ISSUE THREAD

**Issue by cmm** [nix-community/emacs-overlay#350]
(as opposed to the "package" overlay, that is)

The reason I'm asking is that I'm interested in this repo for the purpose of deriving an Emacs that uses a _released_ core Emacs (i.e. one from unadulterated Nixpkgs) + latest MELPA packages as required by my config.

Thus it would make sense for me to opt out of the "emacs" overlay and use only the "package" one, which is not currently an option because `emacsWithPackagesFromUsePackage` is in the former and not in the latter.

This is admittedly a theoretical problem right now because the "emacs" overlay does not shadow Nixpkgs's "emacs" attribute, but will become an actual problem when Nixpkgs (shortly, hopefully) grows its own "emacs-pgtk" attribute (https://github.com/NixOS/nixpkgs/pull/246203).   The coming name clash can be solved by renaming this overlay's "emacs-pgtk" to something else so it does not shadow anything, but still I wonder whether `emacsWithPackagesFromUsePackage` attribute is just in the wrong overlay, since putting it in "package" would make the whole issue moot.

**Comment by jian-lin** [comment]
> The coming name clash can be solved by renaming this overlay's "emacs-pgtk" to something else so it does not shadow anything

Agreed.  Considering existing names in this overlay, `emacs-git-pgtk` is a good candidate.

> putting it in "package" would make the whole issue moot

This introduces another issue for users who want to use `emacsWithPackagesFromUsePackage` together with elisp packages from Nixpkgs instead of this overlay.  I think this issue affects more users.

`emacsWithPackagesFromUsePackage` is actually a wrapper like `emacs.pkgs.withPackage`.  It is not an Emacs variant nor a Emacs lisp package.  Another solution is to put `emacsWithPackagesFromUsePackage` into a separate `wrapper` overlay.

Unfortunately, both of these solutions are breaking changes.

WDYT?

**Comment by jian-lin** [comment]
cc @adisbladis  @leungbk

**Comment by adisbladis** [comment]
It's in the overlay because it's too hacky to be moved into nixpkgs.
If you'd like to use this function separately from the rest feel free to reorganise the flake overlay outputs & submit a PR.
