### ISSUE TITLE
Changes to emacsWithPackagesFromUsePackage break compatibility with literate Emacs configs

### ISSUE THREAD

**Issue by Sorixelle** [nix-community/emacs-overlay#44]
While the changes in #43 are cool and all, and probably the best way to go about this, it's caused my configs to break. My Emacs Lisp configuration is defined in a Org-mode document, which Emacs reads with `org-babel-load-file`. Since the new implementation expects a Elisp file, which my config isn't, the config just fails to evaluate.

I could just convert my config to plain Elisp, but I'd really prefer not to if possible. Maybe some flag could be added to revert to the old "grep for `use-package`" implementation? Not sure what the best way to handle this is.

Sorry to bother you all with a weird edge case :sweat_smile:

**Comment by terlar** [comment]
I think we could add a boolean option such as tangle or orgConfig, which would do something like this before processing the elisp:
```
emacs --batch -Q \
  *.org \
  -f org-babel-tangle
```

If you want a workaround for now you could use this together with `runCommand` on your input.
Probably something like this:
```nix
let
  tangledOrgConfig = pkgs.runCommand "tangled-emacs-config" {} ''
    cp ${./init.org} init.org
    ${pkgs.emacs}/bin/emacs --batch -Q init.org -f org-babel-tangle
    cp init.el $out
  '';
in { config = builtins.readFile tangledOrgConfig; }
```

**Comment by adisbladis** [comment]
It was always meant to work only with elisp files and the fact that the old hacky solution worked with org files was coincidental.

I will not be adding a bool option to tangle org configs.
If you're using an org config I suggest you do what @terlar is showing.

**Comment by adisbladis** [comment]
My previous comment was a bit dismissive, while I stand behind what I said I want to elaborate a bit on why:
Using `builtins.readFile someDerivation` comes with the same downsides as import-from-derivation.

- The derivation may be garbage collected at any time since it's not referenced by any outputs
- It pauses the evaluator while it builds the intermediate derivation

And while it may be fine for you to do so I don't want to encourage and officially support it, that's why I think it's better for each individual to tangle their own configurations.

That said: I would be happy to accept an abstraction that creates a tangle derivation, either here or in nixpkgs.

**Comment by adisbladis** [comment]
I have fixed this by allowing passing paths as `config` & auto-tangle files ending with `.org` in https://github.com/nix-community/emacs-overlay/commit/c9e1c8cb77bb9bde350be271616bbbbce8e14bd6.
