### ISSUE TITLE
Is native-comp enabled by default now?

### ISSUE THREAD

**Issue by balaclava-guy** [nix-community/emacs-overlay#441]
Maybe I'm just being dim here, but I can't seem to find any reference apart from a single ambiguous (to me) line of code ... the emacs docs state emacs needs to be built with native-comp, so if this is already being enabled it would be good to mention explicitly in the docs?

**Comment by leungbk** [comment]
As described in the November 2022 release notes, the default behavior since that time has been to build with native compilation (https://github.com/nixos/nixpkgs/blob/9f4201bf3cfe0f0b0d283ca907c6ce8c5ff1d13b/nixos/doc/manual/release-notes/rl-2211.section.md?plain=1#L40-L42), but it remains possible to build newer Emacsen with native compilation disabled by overriding the `withNativeCompilation` flag.
