### ISSUE TITLE
collision on desktop file

### ISSUE THREAD

**Issue by mogorman** [nix-community/emacs-overlay#58]
lately when I nixos-rebuild switch i have been getting collisions on the desktop file. I simply remount my store as rw and delete the old file and then switch again and it works without a problem.

collision between `/nix/store/kn2s50qdingfj1fjxlawz3sgwadkmwzr-emacs-gcc-with-packages-20200814.0/share/applications/emacsclient.desktop' and `/nix/store/n6llb7j59m0zyc01ki0vdi06frm1cbjc-emacsclient.desktop/share/applications/emacsclient.desktop'

**Comment by willbush** [comment]
I'm getting this too, but with emacsGit (didn't know there was a emacsGcc, I'll have to give that a try) when I [updated my pinned emacs-overlay revision](https://github.com/willbush/system/commit/a32ea770271bdc9eb6473aa2139ec66fc2ae10bd):

```
collision between
`/nix/store/airfi3n2f9w78cd9l9y55hwbl95mag8p-emacs-git-with-packages-20200816.0/share/applications/emacsclient.desktop'
and
`/nix/store/dz068b7fv0pybil9dghih3gc0v796id6-emacsclient.desktop/share/applications/emacsclient.desktop'
```

I got around the issue by commenting out `client.enable = true`:

```nix
services.emacs = {
  enable = true;
  # client.enable = true;
};
```

Which comes from home-manager here: [home-manager/modules/services/emacs.nix](https://github.com/rycee/home-manager/blob/a3dd580adc46628dd0c970037b6c87cff1251af5/modules/services/emacs.nix#L55)

I think I rather whatever else is generating the desktop file not generate it. It makes more sense to me that the `services.emacs` would provide that because without `services.emacs.enable = true` launching the desktop file does nothing.

**Comment by willbush** [comment]
I'm no longer getting this collision issue.

**Comment by adisbladis** [comment]
This seems to be fixed, closing.
