### ISSUE TITLE
Document use with Emacs

### ISSUE THREAD

**Issue by rswgnu** [nix-community/emacs-overlay#7]
Emacs users unfamiliar with Nix will come here for the access to up-to-date Elpa and Melpa libraries as well as Emacs 27 pre-releases.  Therefore, you should explain in detail the steps needed to:

1. Build Emacs 27 and run it.

2. Configure non-Nix-built releases of Emacs to reference the emacs-overlay Elpa and Melpa archives.

When writing a README, always try to think like someone who has never heard of your package is reading it for the first time and wants to understand what it includes, what it requires and how to actually use it.

Just my thoughts.  Great idea by the way.

**Comment by adisbladis** [comment]
I'd be happy to incorporate any documentation changes that make this overlay easier to use. Would you be willing to make a pull request with your suggested changes?

**Comment by rswgnu** [comment]
I would love to help but I am fully committed with other work nowadays.  I
just wanted to get you thinking in this direction.

**Comment by adisbladis** [comment]
1. should be fairly obvious to anyone with some Nix experience (some Nix experience is assumed to be able to use the overlay)
2. Is not trivially possible and not supported.

We could certainly improve documentation but since there is nothing really actionable in this issue I'll close it.

**Comment by IgorGee** [comment]
Hi, I guess I'm the demographic @rswgnu is talking about.

I'm having some trouble understanding how to use this overlay in conjunction with this [documentation](https://nixos.org/nixpkgs/manual/#chap-overlays)

I'm sure it's due to my lack of experience with both nix and overlays. I understand it's not the responsibility of this specific repo to hold the hands of inexperienced nix users, but I would appreciate any help. I'll happily submit a PR with a more detailed process once I'm successful.

I've tried:
## tacking fetchTarball snippet to my `~/.config/nixpkgs/config.nix`
```
{
  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
    }))
  ];
}
```

## making an overlays folder, with the contents being this git repo

**Result**: 
```
error: infinite recursion encountered, at undefined position
```

## making an overlays folder, with an `emacs.nix` file symlinking to `default.nix` of this repo

**Result**:
```
error: selector 'emacsGit' matches no derivations
```

## making an overlays.nix file with the contents being the array:
```
[
   (import (builtins.fetchTarball {
     url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
   }))
]
```

**Result**: 
```
unpacking 'https://github.com/nix-community/emacs-overlay/archive/master.tar.gz'
...
error: selector 'emacsGit' matches no derivations
```

With each of those attempts, I did the following set of commands:
`nix-channel --update nixpkgs; nix-env -u "*"`
`nix-env -i emacsGit`

**Comment by CarlOlson** [comment]
I too would like some hand holding. Tell us what we need to do from a fresh installation. This should be "actionable".

**Why is this needed?** There are too many ways to do overlays in Nix. And when casual users look at maintainers configurations for examples we see even more arcane methods. The lack of good on-boarding material and the hostile attitudes of _some_ members makes NixOS unpleasant sometimes. NixOS is wonderful, but there seems to be a big opportunity for improvement in the human side of things.

**Why do we want emacs 27?** It has beneficial features and is in no way unstable. The native JSON parsing is a nontrivial improvement for many who use LSP-based modes.

Just for some context. I've ran NixOS for about 5 years because it saves time. However, I touch my configuration files rarely, so Nix knowledge doesn't stick in my head. I don't mean for this to be accusatory, but not having emacs 27 as an easy installation wastes a lot of time. Both our time for searching and maintainers's time for having to deal with our complaints. I'm honestly sorry that this contributes to that.

**Comment by xinyifly** [comment]
@IgorGee Hi, I have successfully installed Emacs 27 with:

~/.config/nixpkgs/overlays.nix

```nix
[
  (import (builtins.fetchTarball {
    url = https://github.com/nix-community/emacs-overlay/archive/2cf83a356fc3eef7b1ee22e4843482fedd21e545.tar.gz;
  }))
]
```

And:

```bash
nix-env -iA nixos.emacsUnstable
```

Note that with master branch, I get an error about `nativeComp` currently:

```nix
[
  (import (builtins.fetchTarball {
    url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
  }))
]
```

**Comment by IgorGee** [comment]
@xinyifly Thank you! I've learned a bit more about nix recently and realized there's an important distinction between `nixpkgs` and `nixos`, which is where a good chunk of my confusion stemmed from.

Your solution does work for me as a `nixpkgs` user via this command:

`nix-env -iA nixpkgs.emacsUnstable`

`emacsGit` also works.
