### ISSUE TITLE
gccemacs: External packages' native-compiled code won't get stored

### ISSUE THREAD

**Issue by leungbk** [nix-community/emacs-overlay#74]
``` nix
with (import <nixpkgs> {
  overlays = [ (import (builtins.fetchTarball {
    url = https://github.com/nix-community/emacs-overlay/archive/master.tar.gz;
  })) ]; });

(emacsPackagesGen emacsGcc).emacsWithPackages (epkgs: (with epkgs; [
  evil
]))
```

When running `nix-build` with something like the above on recent revs of this overlay, I get numerous errors of this form:

```
In toplevel form:
evil-command-window.el:36:1: Error: Can't find a writable directory in `comp-eln-load-path'
Compiling /nix/store/w1jd99yn8dgdqxgim2mmxbcz3060vlii-emacs-evil-20201008.1515/share/emacs/site-lisp/elpa/evil-20201008.1515/evil-commands.el...
ad-handle-definition: `evil-mode' got redefined
```

**Comment by tadfisher** [comment]
For byte-compiling, we add the package's lisp directory using [`addToEmacsLoadPath`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/emacs/setup-hook.sh#L1-L8). When compiling, we'll need to add `$out/share/emacs/native-lisp` to `comp-eln-load-path` as by default it will try to use `~/.emacs.d/eln-cache/`, which won't work in the builder environment.

We'll also need to add `"${profileDir}/share/emacs/native-lisp/"` to `comp-eln-load-path` in `site-start.el`, similar to how we handle [`load-path`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/site-start.el#L13-L23).

@adisbladis You added native-comp support to the generic package builder here: https://github.com/NixOS/nixpkgs/commit/e89082346762164f5a9f7f3ebc3afa13fb964718

**Comment by collares** [comment]
I updated to today's nixos-unstable and I am getting a bunch of compilation failures (for example, `org-plus-contrib` says `Done (Total of 0 files compiled, 200 failed)`). I see a bunch of 
```
Debugger entered--Lisp error: (native-compiler-error-empty-byte "/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-..." "/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-...")
  signal(native-compiler-error-empty-byte ("/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-..." "/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-..."))
  comp--native-compile("/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-...")
  batch-native-compile()
  command-line-1(("--eval=(add-to-list 'comp-eln-load-path \"/nix/stor..." "-f" "batch-native-compile" "/nix/store/szl4z641xrf5zswk5fjwyi4hys1fkpr0-emacs-..."))
  command-line()
  normal-top-level()
```
and many requires fail with a `file-missing` error. I use this overlay (tested with commit `48efc8f`) as follows
```
pkgs.emacsWithPackagesFromUsePackage {
  config = builtins.readFile /home/collares/.emacs.d/init.el;
  package = pkgs.emacsGcc;
  alwaysEnsure = true;
  extraEmacsPackages = epkgs: [ epkgs.desktop-environment epkgs.org-plus-contrib ];
}
```

**Comment by collares** [comment]
From a quick inspection of emacs' source code, I think directories in `comp-eln-load-path` must be slash-terminated. I will test this and edit this comment with the results.

**Comment by collares** [comment]
In decreasing order of importance, here's what's causing the above messages. First, the issues:

1. The `file-missing` errors actually matter. When a file requires another file from the same directory, compilation fails because the current package's directory is not in `load-path`. In other words, `setupHook` is only called for dependencies of a package, not for the package itself, and that breaks compilation. I don't know what the cleanest way to fix this is.
1. Because the trailing slash is not missing in `generic.nix`, only `site-start.eln` gets written to the wrong place. However, it's probably the case that emacs cannot find the eln files afterwards. I will submit a small PR to fix this just in case.

The non-issues:

1. The `Done (Total of 0 files compiled, 200 failed)` message comes from elpa2nix, which calls `package-unpack`. This is just noise. Incidentally, package.el has a package-native-compile variable, which I guess is useless for Nix.
1. The native compiler is just noisy when the file contains nothing compilable (that is, if the byte-compiler would generate an empty .elc), I think. This causes the `native-compiler-error-empty-byte` error.

**Comment by leungbk** [comment]
I think the upstream patch should take care of this?

**Comment by collares** [comment]
Item 1 from https://github.com/nix-community/emacs-overlay/issues/74#issuecomment-751131321 is still pending, but that only affects files that require other files from the same directory.

**Comment by tadfisher** [comment]
Something about native-comp is breaking `git-commit` somehow. Compiling with `emacsGcc` or `emacsPgtkGcc` results in the following:

<details>
<summary>Log output for `(emacsPackagesFor emacsPgtkGcc).git-commit`</summary>
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/6yrf5p0li2k7ajwyjncjzpisxwria7cr-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
@nix { "action": "setPhase", "phase": "installPhase" }
installing
  INFO     Scraping files for git-commit-autoloads.el... 
  INFO     Scraping files for git-commit-autoloads.el...done
Checking /nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-git-commit-20210102.1242/share/emacs/site-lisp/elpa/git-commit-20210102.1242...
Compiling /nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-git-commit-20210102.1242/share/emacs/site-lisp/elpa/git-commit-20210102.1242/git-commit-autoloads.el...
Compiling /nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-git-commit-20210102.1242/share/emacs/site-lisp/elpa/git-commit-20210102.1242/git-commit-pkg.el...
Compiling /nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-git-commit-20210102.1242/share/emacs/site-lisp/elpa/git-commit-20210102.1242/git-commit.el...

In toplevel form:
git-commit.el:123:1: Error: Cannot find suitable directory for output in `comp-eln-load-path'
Done (Total of 0 files compiled, 1 failed, 2 skipped)
Debugger entered--Lisp error: (error "transient--init-suffix-key is already defined as s...")
  error("%s is already defined as something else than a gen..." transient--init-suffix-key)
  cl-generic-ensure-function(transient--init-suffix-key)
  cl-generic-define-method(transient--init-suffix-key nil ((obj transient-suffix)) nil #f(compiled-function (obj) #<bytecode -0xa7c7a5fc3895bff>))
  byte-code("\300\301\302\303\302\304%\210\300\301\302\305\306\307%\207" [cl-generic-define-method transient--init-suffix-key nil ((obj transient-suffix)) #f(compiled-function (obj) #<bytecode -0xa7c7a5fc3895bff>) ((obj transient-argument)) t #f(compiled-function (cl--cnm obj) #<bytecode -0xf13bb1fdc884b05>)] 6)
  require(transient)
  load-with-code-conversion("/nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-..." "/nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-..." nil t)
  git-commit-setup-check-buffer()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer git-commit-20210102.1242.el> "/build/packages/git-commit-20210102.1242.el" nil nil "/build/packages/git-commit-20210102.1242.el" (114162937 31))
  find-file-noselect("/build/packages/git-commit-20210102.1242.el")
  command-line-1(("-l" "/nix/store/4jj63z4v1xp13rh2md053dccq920hd45-elpa2n..." "-f" "elpa2nix-install-package" "/build/packages/git-commit-20210102.1242.el" "/nix/store/5a8w97mi76d2kq109iy5g9pzcif3ddrk-emacs-..."))
  command-line()
  normal-top-level()
```
</summary>

Building `(emacsPackagesFor emacsGit).git-commit` doesn't result in the same issue.

**Comment by collares** [comment]
I see this too, but it seems like a very recent regression. Commit 33b8ce865fcfd58538ae2d7c3fff04998fcd3330 from branch feature/native-comp, from five days ago, is working fine.

**Comment by tadfisher** [comment]
Unfortunately, pinning emacs-overlay to that revision will break on `auctex` as they changed distribution formats from `.tar.lz` to plain `.tar`.

**Comment by collares** [comment]
@tadfisher I've verified that compilation does not fail if I revert commit https://github.com/emacs-mirror/emacs/commit/7d7bfbf0346114b116e14a4338ea235d12674f13 then commit https://github.com/emacs-mirror/emacs/commit/9973019764250ac1f4d77a6b426cdd9c241151c5. If you want these changes already applied, https://github.com/collares/emacs/tree/revert-package-el-changes has them and https://github.com/collares/emacs-overlay/tree/revert-package-el-changes is pointed at my Emacs fork. I will file an Emacs bug as soon as I have a minimized example.

**Comment by collares** [comment]
This might not be a bug in upstream emacs, since `pkgs/build-support/emacs/elpa2nix.el` calls `(package-initialize)` explicitly and https://github.com/emacs-mirror/emacs/commit/9973019764250ac1f4d77a6b426cdd9c241151c5 replaces a bunch of `(package-initialize)` by `(package-activate-all)`.

That being said, if you take a look at the command line in the above stack trace, the error does not happen when batch-native-compiling, but rather when running `elpa2nix-install-package`. It is, therefore, a bit surprising that there would be a difference of behavior between `emacsGit` and `emacsGcc`. Not super surprising, though, because there's a warning about `comp-eln-load-path` suggesting that `transient` is being native-compiled when `require`d.

**Comment by collares** [comment]
I tried isolating the failure by downloading the relevant MELPA packages and doing stuff like
```
$ /nix/store/gq1nicgn7bsa571fyphsbfh8g6vgcpki-emacs-gcc-20210109.0/bin/emacs -Q --batch --eval "(add-to-list 'load-path \"/home/collares\")" --eval "(setq comp-eln-load-path '(\"/home/collares/\"))" -l ~/elpa2nix.el --eval '(elpa2nix-install-file "~/dash-20210111.1247.tar")'
$ /nix/store/gq1nicgn7bsa571fyphsbfh8g6vgcpki-emacs-gcc-20210109.0/bin/emacs -Q --batch --eval "(add-to-list 'load-path \"/home/collares\")" --eval "(setq comp-eln-load-path '(\"/home/collares/\"))" -l ~/elpa2nix.el --eval '(elpa2nix-install-file "~/transient-20210103.1546.tar")'
$ /nix/store/gq1nicgn7bsa571fyphsbfh8g6vgcpki-emacs-gcc-20210109.0/bin/emacs -Q --batch --eval "(add-to-list 'load-path \"/home/collares\")" --eval "(setq comp-eln-load-path '(\"/home/collares/\"))" -l ~/elpa2nix.el --eval '(elpa2nix-install-file "~/git-commit-20210102.1242.el")'
```
but I can't reproduce the failure outside the Nix builder yet. Unfortunately I won't have much time to work on this before the weekend, so any help reporting this upstream is much appreciated.

**Comment by collares** [comment]
I've debugged the `git-commit.el` problem. There are two parts to the problem.

1. The `git-commit.el:123:1: Error: Cannot find suitable directory for output in `comp-eln-load-path'` error when running `elpa2nix-install-package`. This one happened before, and it occurs because git-commit.el:123 (`(require 'transient)`) for some reason starts native compilation, which then errors out because the native load path is not set up when running `elpa2nix-install-package`. I don't know if this is an attempt to compile a trampoline or a package, but we should probably disable native compilation here since we do it later anyway.
2. https://github.com/emacs-mirror/emacs/commit/7d7bfbf0346114b116e14a4338ea235d12674f13 recently changed autoload behavior in some cases, and this seems to have exposed a bug in native-comp. I have filed https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-01/msg00814.html for this.

Point 1 is definitely easier to fix on our side. It could be as simple as setting `comp-deferred-compilation` to nil when running `elpa2nix-install-package`. If that works, I'll send a PR to nixpkgs, but if it doesn't help is appreciated :)

**Comment by collares** [comment]
As of yesterday, the workaround in https://github.com/NixOS/nixpkgs/pull/109370 fixes issue 1 and makes `git-commit` compile. Issue 2 is being investigated upstream.

**Comment by jhenahan** [comment]
I have a branch off of `20.09` at https://github.com/jhenahan/nixpkgs/tree/emacs-fixes that includes your patches (and some tweaks to get them applying to `20.09`) for anyone looking for something to use without having to maintain a nixpkgs checkout or rebuild the world.

**Comment by collares** [comment]
@jhenahan That's very useful, thanks!

By the way, at this very moment no packages are being native compiled in emacs-overlay (at least on my machine). This is a regression from #105 and is being discussed there.

**Comment by collares** [comment]
The main work on the native-comp infrastructure (done by @tadfisher) is in nixpkgs master, and so are a couple of fixes I made. So I believe this issue will be resolved once the channels update.

If you open emacsGcc and see compilation happening, it probably means that that a package has a special build process which wasn't adapted to work with native compilation yet. In my machine, this happens only with mu4e.
